In [1]:
import numpy as np

import econpy as ep
from econpy.lin.tests import test_err

In [3]:
seed = 179
rng = np.random.default_rng(seed)

n = 1001
d = 2

X = rng.standard_normal((d, n))
b = np.array([1., 2.])
w = rng.uniform(0, 1, n)

Y_err = rng.standard_normal((1, n))
Y = b @ X + Y_err

ep.lin.est.ols(Y, X, ep.lin.err.hc1)
ep.lin.est.wls(Y, X, w, ep.lin.err.hc1)

(array([[1.01209159, 1.99392029]]),
 array([[[1.19092651e-03, 9.15351248e-05],
         [9.15351248e-05, 1.19738269e-03]]]))

In [ ]:
seed = 179
rng = np.random.default_rng(seed)

n = 1001
r = 3
d = 2


Z = rng.standard_normal((r, n))
g = np.array([[1., 2., 0.],
              [0., 1., 1.]])
b = np.array([[1., 2.]])
w = rng.uniform(0, 1, n)
X_err = rng.standard_normal((d, n))
X = g @ Z + X_err
Y_err = rng.standard_normal((1, n))
Y = (b @ g) @ Z + Y_err

ep.lin.est.ols(Y, X, ep.lin.err.hc1)
ep.lin.est.wls(Y, X, w, ep.lin.err.hc1)

In [5]:
test_errors.test(ep.linear.errors.get_hc2_err)

Error rate OLS: 67.50% Error rate WLS: 68.20%
Error rate OLS: 68.20% Error rate WLS: 67.50%
Error rate OLS: 68.90% Error rate WLS: 66.60%

Error rate TSLS: 68.40% Error rate WTSLS: 67.90%
Error rate TSLS: 70.90% Error rate WTSLS: 69.60%
Error rate TSLS: 69.70% Error rate WTSLS: 71.00%


In [6]:
test_errors.test(ep.linear.errors.get_hc3_err)

Error rate OLS: 67.40% Error rate WLS: 68.10%
Error rate OLS: 68.20% Error rate WLS: 67.40%
Error rate OLS: 68.90% Error rate WLS: 66.60%

Error rate TSLS: 68.30% Error rate WTSLS: 67.70%
Error rate TSLS: 70.80% Error rate WTSLS: 69.60%
Error rate TSLS: 69.50% Error rate WTSLS: 70.90%


In [2]:
def print_estimate(models, prm_names):
    for name in prm_names:
        print(f" {name:<10}", end="")
    print()
    for prm, prm_err in models:
        for reg, reg_err in zip(prm, prm_err):
            for est in reg:
                print(f" {est:<8.3g}  ", end="")
            print()
            for err in reg_err.diagonal()**0.5:
                print(f"({err:<8.3g}) ", end="")
            print()

In [3]:
seed = 179
rng = np.random.default_rng(seed)

In [130]:
n = 1001
d = 5

X = rng.standard_normal((d, n))
b = rng.uniform(0, 1, (1, d))
w = rng.uniform(0, 1, n) * 10

tries = 1000
summ = 0

for _ in range(tries):
    Y_err = rng.standard_normal((1, n))
    Y = b @ X + Y_err
    prm, prm_err = estimate_wls(Y, X, w, get_hc1_err)
    dev = prm - b
    summ += np.abs(dev[0][0]) < (prm_err[0].diagonal()[0])**0.5

print(summ / tries)

0.68


In [135]:
n = 1001
d = 5
r = 10

Z = rng.standard_normal((r, n))
g = rng.uniform(0, 1, (d, r))
b = rng.uniform(0, 1, (1, d))
b_err = rng.uniform(0, 1, (1, d))
w = rng.uniform(0, 1, n) * 10

tries = 1000
summ = 0

for _ in range(tries):
    X_err = rng.standard_normal((d, n))
    X = g @ Z + X_err
    Y_err = rng.standard_normal((1, n))
    Y = (b @ g) @ Z + b_err @ X_err + Y_err
    prm, prm_err, _, _ = estimate_wtsls(Y, X, Z, w, get_hc1_err)
    dev = prm - b
    summ += np.abs(dev[0][0]) < (prm_err[0].diagonal()[0])**0.5

print(summ / tries)

0.687


In [168]:
n = 300
d = 5
r = 10

Z = rng.standard_normal((r, n))
g = rng.uniform(0, 1, (d, r))
b = rng.uniform(0, 1, (1, d))
b_err = rng.uniform(0, 1, (1, d))
w = rng.uniform(0, 1, n) * 10

X_err = rng.standard_normal((d, n))
X = g @ Z + X_err
Y_err = rng.standard_normal((1, n))
Y = (b @ g) @ Z + b_err @ X_err + Y_err

print_estimate(
    (
        estimate_ols(Y, X, get_hc0_err),
        estimate_ols(Y, X, get_hc1_err),
        estimate_ols(Y, X, get_hc2_err),
        estimate_wls(Y, X, w, get_hc1_err),
        estimate_wls(Y, X, w, get_hc2_err)),
    ('a', 'b', 'c', 'd', 'e'))
print()
print_estimate(
    (
        estimate_tsls(Y, X, Z, get_hc0_err)[:2],
        estimate_tsls(Y, X, Z, get_hc1_err)[:2],
        estimate_tsls(Y, X, Z, get_hc2_err)[:2],
        estimate_wtsls(Y, X, Z, w, get_hc1_err)[:2],
        estimate_wtsls(Y, X, Z, w, get_hc2_err)[:2]),
    ('a', 'b', 'c', 'd', 'e'))
b

 a          b          c          d          e         
 0.637      0.698      0.371      0.84       0.884     
(0.0391  ) (0.0478  ) (0.0439  ) (0.0458  ) (0.0415  ) 
 0.637      0.698      0.371      0.84       0.884     
(0.0394  ) (0.0482  ) (0.0442  ) (0.0461  ) (0.0419  ) 
 0.637      0.698      0.371      0.84       0.884     
(0.0396  ) (0.0483  ) (0.0445  ) (0.0464  ) (0.042   ) 
 0.603      0.675      0.427      0.861      0.887     
(0.0469  ) (0.056   ) (0.0585  ) (0.062   ) (0.0493  ) 
 0.603      0.675      0.427      0.861      0.887     
(0.0476  ) (0.0567  ) (0.0597  ) (0.063   ) (0.0499  ) 

 a          b          c          d          e         
 0.427      0.858      0.565      0.746      0.878     
(0.0563  ) (0.0754  ) (0.0597  ) (0.08    ) (0.0693  ) 
 0.427      0.858      0.565      0.746      0.878     
(0.0623  ) (0.0834  ) (0.066   ) (0.0885  ) (0.0766  ) 
 0.427      0.858      0.565      0.746      0.878     
(0.057   ) (0.0762  ) (0.0604  ) (0.0809  ) (0.

array([[0.44178532, 0.87867674, 0.62825521, 0.70674418, 0.82222899]])

In [65]:
n = 1001
d = 5
group_num = 100

X = rng.standard_normal((d, n))
fe1 = rng.integers(0, 10, n)
fe2 = rng.integers(0, 5, n)
fe3 = rng.integers(0, 7, n)
int_fes = (fe1, fe2, fe3)
real_fes = tuple()
real_fe_weights = tuple()

Y = absorb_fes((X.copy(),), int_fes, real_fes, real_fe_weights)[0]

5 0.0001


In [66]:
absorb_fes((Y.copy(),), int_fes, real_fes, real_fe_weights)

3 0.0001


(array([[ 0.61976706,  0.67286403,  0.01455376, ..., -0.88299497,
          0.11287554,  0.46086876],
        [ 1.32596792, -0.01723872, -2.0954315 , ...,  3.29437931,
         -0.23848466,  0.83593472],
        [-0.98540658, -0.6730087 , -0.58328141, ...,  1.09590977,
          0.29211602, -0.01794524],
        [-2.23957403, -0.59031217,  0.58649004, ..., -0.65545657,
         -0.65380379,  0.04834854],
        [-0.55432767,  0.17049261, -0.92657864, ..., -0.43242741,
         -0.76866692, -1.14397485]]),)

In [67]:
Y

array([[ 0.61976786,  0.67286432,  0.01455404, ..., -0.88299544,
         0.11287669,  0.46086823],
       [ 1.32596916, -0.01723833, -2.09543133, ...,  3.29437887,
        -0.23848368,  0.83593404],
       [-0.98540586, -0.6730085 , -0.58328143, ...,  1.09590962,
         0.29211638, -0.01794555],
       [-2.23957478, -0.59031239,  0.58648975, ..., -0.65545607,
        -0.65380515,  0.04834905],
       [-0.55432788,  0.17049266, -0.92657831, ..., -0.4324277 ,
        -0.76866638, -1.143975  ]])

In [68]:
X

array([[ 0.44786132,  0.61150628, -0.04291387, ..., -0.70656259,
         0.19839476,  0.51654182],
       [ 1.43690275,  0.05921647, -1.98932377, ...,  3.14779131,
        -0.35284057,  1.02808867],
       [-0.94460508, -0.83203732, -0.36515009, ...,  1.11357138,
         0.25777299,  0.21750395],
       [-2.3248494 , -0.85107414,  0.48450332, ..., -0.7746397 ,
        -0.43920506,  0.39139707],
       [-0.53589184,  0.03376505, -0.97536275, ..., -0.44714407,
        -0.69569879, -1.21082812]])